### ISSUE TITLE
"series name" tag is not always present

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/kukur#132]
Not all series have a "series name" tag, while the `search()` flight method asserts that the tag exists.

https://github.com/timeseer-ai/kukur/blob/b2687dea664b10c85d364b21aa5d318237bb5365/kukur/flight.py#L84

This causes an `AssertionError`.

**Comment by WouterWouters** [comment]
Validated it by using a series that doesn't have a series name as a tag and use the search function in Kukur
