### ISSUE TITLE
Support Elasticsearch

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/kukur#223]
Add support for Elasticsearch:

- [ ] prepare realistic sensor metadata (join multiple tables)
- [ ] prepare realistic sensor data
- [ ] list available series based on a query
- [ ] read metadata for a series based on a query
- [ ] allow reading data based on a query

Support reading inside the returned document tree.

Ensure that SQL injection is not possible.

**Comment by smeganck** [comment]
@jhoekx

**Comment by jhoekx** [comment]
Validated with slight adjustments in 1417cdf0022dece45e7152908f182a699cc0a7c3.
