### ISSUE TITLE
Support 'tags' and 'fields' in SeriesSelectors

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/kukur#28]
Time Series in Data historians can generally be identified by a `series name` only. Modern time series databases provide some structure that we currently don't expose.

For example, InfluxDB exposes 'tags' and 'fields'. Tag values are indexed and allow finding the wanted time series. A field indicates which 'column' needs to be selected.

Add both to `SeriesSelector` so it becomes:

```
class SeriesSelector:
    source: str
    tags: Dict[str, str]
    field: Optional[str]
```

The `series name` is available as a tag.

Existing sources can be queried using:

```
SeriesSelector(source, {"series name": "<name>"}, "value")
```

In order to keep compatibility with old versions, automatically turn a `"name"` field in the `from_json()` method to a tag.

**Comment by WouterWouters** [comment]
Closed by 1590494312d9b14e63f69cc3c890f7bd3f71558e
