### ISSUE TITLE
Support partitioning delta lakes

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/kukur#96]
Asking for partitioned data is straightforward:

```
table.to_pyarrow_table([("name", "=", "tsai_01_AI_211_01.PV"), ("year", "in", ["2021"]), ("month", "in", ["2", "3"])])
```

In the source, allow defining partitions:

```
[source.Delta]
type = "delta"
uri = "..."
tag_columns = ["name"]
data_query_timezone = "UTC"

[[source.Delta.partitions]]
origin = "tag"
key = "location"

[[source.Delta.partitions]]
origin = "timestamp"
key = "MONTH"
format = "%Y-%m"

[[source.Delta.partitions]]
origin = "timestamp"
key = "DAY"
# format = "%d" # the default when no format is given.
```

The request time range needs to be translated into the correct partitions, taking an optional `data_query_timezone` into account.

If low-level access to the request data is required, the `DeltaSource` could no longer use `BaseArrowSource`. Extract functions to share the table conversion logic in that case.

**Comment by smeganck** [comment]
@lucasKoeb

**Comment by lucasKoeb** [comment]
Validated by generating new data and saving with partitions, then using the source on timeseer.
